---
- name: Deploy Flask App
  hosts: Sn3
  become: yes

  tasks:
    - name: Install required packages
      package:
        name:
          - python3
          - python3-pip
          - git

    - name: Create the destination folder
      file:
        path: /opt/flask-app
        state: directory

    - name: Clone the repository
      git:
        repo: https://github.com/kemiye01/mid-class.git
        dest: /opt/flask-app

    - name: Install Flask library
      pip:
         name: Flask
         executable: /usr/bin/pip3
         state: present

    - name: Install Flask and its dependencies
      pip:
        name: flask
        chdir: /opt/flask-app

    - name: Start the Flask App
      command: python3 /opt/flask-app/app.py
      async: 1
      poll: 0
